version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskmate-boardservice-task-definition"
        LoadBalancerInfo:
          ContainerName: "taskmate-boardservice-container"
          ContainerPort: 8080