version = 0.1
[default.deploy.parameters]
stack_name = "spring-boot-products"
resolve_s3 = true
s3_prefix = "spring-boot-products"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[snapstart.deploy.parameters]
stack_name = "spring-boot-products-snapstart"
resolve_s3 = true
s3_prefix = "spring-boot-products-snapstart"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[native.deploy.parameters]
stack_name = "spring-boot-products-native"
resolve_s3 = true
s3_prefix = "spring-boot-products-native"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[native-arm.deploy.parameters]
stack_name = "spring-boot-products-native-arm"
resolve_s3 = true
s3_prefix = "spring-boot-products-native-arm"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
